---
title: "Основы обработки данных с помощью R и Dplyr"
subtitle: "Основы обработки данных с помощью R и Dplyr"
author: "deesshii@yandex.ru"
format:
  md:
    output-file: README.md
---

## Цель работы:

1. Развить практические навыки использования языка программирования R для
обработки данных
2. Закрепить знания базовых типов данных языка R
3. Развить практические навыки использования функций обработки данных пакета
dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1. Программное обеспечение Windows 10 
2. Rstudio Desktop
3. Наше рабочее окружение

```{r}
sessionInfo()
```
     
       
 
## План

Используя R и среду разработки RstudioIDE, выполнить задания.

## Шаги:   
```
> library(dplyr)

Присоединяю пакет: ‘dplyr’

Следующие объекты скрыты от ‘package:stats’:

    filter, lag

Следующие объекты скрыты от ‘package:base’:

    intersect, setdiff, setequal, union
> starwars %>% nrow()
[1] 87
> starwars
# A tibble: 87 × 14
   name     height  mass hair_color skin_color eye_color birth_year sex   gender
   <chr>     <int> <dbl> <chr>      <chr>      <chr>          <dbl> <chr> <chr> 
 1 Luke Sk…    172    77 blond      fair       blue            19   male  mascu…
 2 C-3PO       167    75 NA         gold       yellow         112   none  mascu…
 3 R2-D2        96    32 NA         white, bl… red             33   none  mascu…
 4 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
 5 Leia Or…    150    49 brown      light      brown           19   fema… femin…
 6 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
 7 Beru Wh…    165    75 brown      light      blue            47   fema… femin…
 8 R5-D4        97    32 NA         white, red red             NA   none  mascu…
 9 Biggs D…    183    84 black      light      brown           24   male  mascu…
10 Obi-Wan…    182    77 auburn, w… fair       blue-gray       57   male  mascu…
# ℹ 77 more rows
# ℹ 5 more variables: homeworld <chr>, species <chr>, films <list>,
#   vehicles <list>, starships <list>
# ℹ Use `print(n = ...)` to see more rows
> starwars %>% nrow()
[1] 87
> starwars %>% ncol()
[1] 14
> 
> starwars %>% glimpse()
Rows: 87
Columns: 14
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Leia Or…
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 2…
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.…
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brown", N…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "light", "light", "…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "blue",…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, …
$ sex        <chr> "male", "none", "none", "male", "female", "male", "female",…
$ gender     <chr> "masculine", "masculine", "masculine", "masculine", "femini…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan", "T…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", "Huma…
$ films      <list> <"A New Hope", "The Empire Strikes Back", "Return of the J…
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>, "Imp…
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced x1",…
> starwars$species %>% unique() %>% length()
[1] 38
> starwars %>%
+     filter(height == max(height, na.rm = TRUE)) %>%
+     select(name, height)
# A tibble: 1 × 2
  name        height
  <chr>        <int>
1 Yarael Poof    264
> starwars %>%
+   filter(height < 170) %>%
+   select(name, height)
# A tibble: 22 × 2
   name                  height
   <chr>                  <int>
 1 C-3PO                    167
 2 R2-D2                     96
 3 Leia Organa              150
 4 Beru Whitesun Lars       165
 5 R5-D4                     97
 6 Yoda                      66
 7 Mon Mothma               150
 8 Wicket Systri Warrick     88
 9 Nien Nunb                160
10 Watto                    137
# ℹ 12 more rows
# ℹ Use `print(n = ...)` to see more rows
> print(n = 22)
Ошибка в print.default(n = 22) : аргумент "x" пропущен, умолчаний нет

> starwars %>%
+   mutate(BMI = mass / (height/100)^2) %>%
+   select(name, mass, height, BMI)
# A tibble: 87 × 4
   name                mass height   BMI
   <chr>              <dbl>  <int> <dbl>
 1 Luke Skywalker        77    172  26.0
 2 C-3PO                 75    167  26.9
 3 R2-D2                 32     96  34.7
 4 Darth Vader          136    202  33.3
 5 Leia Organa           49    150  21.8
 6 Owen Lars            120    178  37.9
 7 Beru Whitesun Lars    75    165  27.5
 8 R5-D4                 32     97  34.0
 9 Biggs Darklighter     84    183  25.1
10 Obi-Wan Kenobi        77    182  23.2
# ℹ 77 more rows
# ℹ Use `print(n = ...)` to see more rows
> starwars %>%
+   mutate(stretch = mass / height) %>%
+   arrange(desc(stretch)) %>%
+   head(10) %>%
+   select(name, mass, height, stretch)
# A tibble: 10 × 4
   name                   mass height stretch
   <chr>                 <dbl>  <int>   <dbl>
 1 Jabba Desilijic Tiure  1358    175   7.76 
 2 Grievous                159    216   0.736
 3 IG-88                   140    200   0.7  
 4 Owen Lars               120    178   0.674
 5 Darth Vader             136    202   0.673
 6 Jek Tono Porkins        110    180   0.611
 7 Bossk                   113    190   0.595
 8 Tarfful                 136    234   0.581
 9 Dexter Jettster         102    198   0.515
10 Chewbacca               112    228   0.491
> starwars %>%
+   group_by(species) %>%
+   summarise(avg_age = mean(birth_year, na.rm = TRUE)) %>%
+   arrange(desc(avg_age))
# A tibble: 38 × 2
   species        avg_age
   <chr>            <dbl>
 1 Yoda's species   896  
 2 Hutt             600  
 3 Wookiee          200  
 4 Cerean            92  
 5 Zabrak            54  
 6 Human             53.7
 7 Droid             53.3
 8 Trandoshan        53  
 9 Gungan            52  
10 Mirialan          49  
# ℹ 28 more rows
# ℹ Use `print(n = ...)` to see more rows
> starwars %>%
+   count(eye_color, sort = TRUE) %>%
+   slice_max(n, n = 1)
# A tibble: 1 × 2
  eye_color     n
  <chr>     <int>
1 brown        21
> starwars %>%
+   mutate(name_length = nchar(name)) %>%
+   group_by(species) %>%
+   summarise(avg_name_length = mean(name_length, na.rm = TRUE))
# A tibble: 38 × 2
   species   avg_name_length
   <chr>               <dbl>
 1 Aleena              12   
 2 Besalisk            15   
 3 Cerean              12   
 4 Chagrian            10   
 5 Clawdite            10   
 6 Droid                4.83
 7 Dug                  7   
 8 Ewok                21   
 9 Geonosian           17   
10 Gungan              11.7 
# ℹ 28 more rows
# ℹ Use `print(n = ...)` to see more rows
```

## Оценка результата

 В результате лабораторной работы мы развили практические навыки использования языка программирования R для
обработки данных. Закрепили знания базовых типов данных языка R. Развили практические навыки использования функций обработки данных пакета
dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Вывод

Закрепили знания базовых типов данных языка R. Развили практические навыки использования функций обработки данных пакета
dplyr – функции select(), filter(), mutate(), arrange(), group_by()